name: Update README.md
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure git with GitHub token
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Modifies readme file
        env:
          REPO: ${{ github.repository }}
        run: |
          npm install
          npm run update_readme

      - if: (success())
        name: Commit changes
        run: |
          git commit -m "Auto updated readme file" -a

      - if: (success())
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true