name: Update README.md
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README.md
        run: |
          echo "Hello, world!" > README.md
          git config --local user.email "cotactearmenion@gmail.com"
          git config --local user.name "Ivan Cotacte"
          git add README.md
          git commit -m "Update README.md"
          git push