name: Update README.md
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure git with GitHub token
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Modifies readme file
        env:
          REPO: ${{ github.repository }}
        run: |
          npm install
          npm run update_readme

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "Changes detected"

      - name: Commit changes
        if: steps.git-check.outputs.stdout == 'Changes detected'
        run: |
          git add README.md
          git commit -m "Auto updated readme file"

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
